<?php

return [
    'mng' => 'Administration',
    'login' => 'Login',
    'logout' => 'Logout',
    'content' => 'Content',
    'inventory' => 'Inventory',
    'ownership' => 'Ownership',
    'ownershipAll' => 'All Ownership',
    'byItem' => 'By Item',
    'newRecord' => 'New Record',
    'editRecord' => 'Edit Record',
    'quality' => 'Quality',
    'articles' => 'Articles',
    'briefs' => 'briefs',
    'currentHighlights' => 'Current Highlights',
    'allHighlights' => 'All highlights',
    'highlights' => 'Highlights',
    'newArticle' => 'New article',
    'newBrief' => 'New brief',
    'newHighlight' => 'New highlight',
    'announcements' => 'Announcements',
    'allAnnouncements' => 'All nnouncements',
    'currentAnnouncements' => 'Current Annoumcements',
    'newAnnouncement' => 'New announcement',
    'edit' => 'Edit',
    'submit' => 'Submit',
    'user' => 'User',
    'editItem' => 'Edit item',
    'editPics' => 'Edit pictures',
    'listAll' => 'List all records',
    'archive' => 'Archive',
    'newItem'=>'New Item',
    'newPerson'=>'New person',
];
