<?php

return [
    'mng' => 'ניהול',
    'login' => 'כניסה',
    'logout' => 'התנתק',
    'content' => 'תכנים',
    'inventory' => 'מלאי',
    'ownership' => 'בעלות',
    'ownershipAll' => 'רשומות בעלות',
    'byItem' => 'רשומות לפריט',
    'newRecord' => 'רשומה חדשה',
    'editRecord' => 'עריכת רשומה',
    'quality' => 'איכות',
    'articles' => 'מאמרים',
    'briefs' => 'תקצירים',
    'currentHighlights' => 'הבזקים תקפים',
    'allHighlights' => 'כל ההבזקים',
    'highlights' => 'הבזקים',
    'newArticle' => 'מאמר חדש',
    'newBrief' => 'תקציר חדש',
    'newHighlight' => 'הבזק חדש',
    'announcements' => 'הודעות',
    'allAnnouncements' => 'כל ההודעות',
    'currentAnnouncements' => 'הודעות תקפות',
    'newAnnouncement' => 'הודעה חדשה',
    'edit' => 'עריכה',
    'submit' => 'עדכן',
    'user' => 'משתמש',
    'editItem' => 'עריכת פריט',
    'editPics' => 'עריכת תמונות',
    'listAll' => 'כל הרשומות',
    'archive' => 'ארכיון',
];
